---
# vars file for ec2
ssh_dir: "{{ local_home }}/.ssh"
ssh_config_filename: config
ssh_config_dir_target: "{{ ssh_dir }}/{{ ssh_config_filename }}"

ec2_my_key: "{{ project_name }}-{{ env }}-key"

ec2_instances_running: {}
ec2_security_groups: {}
ec2_webserver_groups:
  - name: webserver
    description: "Webserver security group"
    vpc_id: "{{ ec2_vpc_default }}"
    region: "{{ ec2_region }}"
ec2_database_groups:
  - name: database
    description: "Mysql security group"
    vpc_id: "{{ ec2_vpc_default }}"
    region: "{{ ec2_region }}"
